# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Pokemon.delete_all
Item.delete_all

#pokemon

Pokemon.create(id: 1, name: 'Bulbasaur', type1:  'Grass', type2: 'Poison', move1: 'Leech Seed',move2: 'Vine Whip', move3: 'Tackle', move4: 'Sleep Powder', hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45)
Pokemon.create(id: 2, name: 'Ivysaur',type1: 'Grass', type2: 'Poison',move1: 'Vine Whip', move2: 'Razor Leaf', move3: 'Sleep Powder', move4: 'Take Down', hp: 60, attack: 62, defense: 63, specialAttack: 80, specialDefense: 80, speed: 60)
Pokemon.create(id: 3, name: 'Venusaur', type1: 'Grass', type2: 'Poison', move1: 'Vine Whip',move2: 'Solarbeam', move3: 'Take Down', move4: 'Sleep Powder', hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80)
Pokemon.create(id: 4, name: 'Charmander', type1: 'Fire', type2: '', move1: 'Ember', move2: 'Growl', move3: 'Scratch', move4: 'Tackle', hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 60)
Pokemon.create(id: 5, name: 'Charmeleon', type1: 'Fire', type2: '', move1: 'Ember', move2: 'Flamethrower', move3: 'Cut', move4: 'Tackle', hp: 58, attack: 64, defense: 58, specialAttack: 80, specialDefense: 65, speed: 80)
Pokemon.create(id: 6, name: 'Charizard', type1: 'Fire', type2: 'Flying', move1: 'Flamethrower', move2: 'Flare Blitz', move3: 'Blast Burn', move4: 'Mega Punch', hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100)
Pokemon.create(id: 7, name: 'Squirtle', type1: 'Water', type2: '', move1: 'Water Gun', move2: 'Tail Whip', move3: 'Scratch', move4: 'Tackle', hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43)
Pokemon.create(id: 8, name: 'Wartortle', type1: 'Water', type2: '', move1: 'Bubblebeam', move2: 'Water Gun', move3: 'Cut', move4: 'Tackle', hp: 59, attack: 63, defense: 80, specialAttack: 65, specialDefense: 80, speed: 58)
Pokemon.create(id: 9, name: 'Blastoise', type1: 'Water', type2: '', move1: 'Hydro Pump', move2: 'Surf', move3: 'Waterfall', move4: 'Take Down', hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78)
Pokemon.create(id: 10, name: 'Caterpie', type1: 'Bug', type2: '', move1: 'String Shot', move2: 'Tackle', move3: 'Tackle', move4: 'Tackle', hp: 45, attack: 30, defense: 35, specialAttack: 20, specialDefense: 20, speed: 45)
Pokemon.create(id: 11, name: 'Metapod', type1: 'Bug', type2: '', move1: 'Harden', move2: 'Harden', move3: 'Harden', move4: 'Harden', hp: 50, attack: 20, defense: 55, specialAttack: 25, specialDefense: 25, speed: 30)
Pokemon.create(id: 12, name: 'Butterfree', type1: 'Bug', type2: 'Flying', move1: 'Aerial Ace', move2: 'Gust', move3: 'Poison Powder', move4: 'Stun Spore', hp: 60, attack: 45, defense: 50, specialAttack: 90, specialDefense: 80, speed: 70)
Pokemon.create(id: 13, name: 'Weedle', type1: 'Bug', type2: 'Poison', move1: 'String Shot', move2: 'Poison Sting', move3: 'Tackle', move4: 'Thrash', hp: 40, attack: 35, defense: 30, specialAttack: 20, specialDefense: 20, speed: 50)
Pokemon.create(id: 14, name: 'Kakuna', type1: 'Bug', type2: 'Poison', move1: 'Harden', move2: 'Harden', move3: 'Harden', move4: 'Harden', hp: 45, attack: 25, defense: 50, specialAttack: 25, specialDefense: 25, speed: 35)
Pokemon.create(id: 15, name: 'Beedrill', type1: 'Bug', type2: 'Poison', move1: 'Pin Missile', move2: 'Fury Attack', move3: 'Acid', move4: 'Pursuit', hp: 65, attack: 90, defense: 40, specialAttack: 45, specialDefense: 80, speed: 75)
Pokemon.create(id: 16, name: 'Pidgey', type1: 'Normal', type2: 'Flying', move1: 'Gust', move2: 'Sand Attack', move3: 'Tackle', move4: 'Quick Attack', hp: 40, attack: 45, defense: 40, specialAttack: 35, specialDefense: 35, speed: 56)
Pokemon.create(id: 17, name: 'Pidgeotto', type1: 'Normal', type2: 'Flying', move1: 'Quick Attack', move2: 'Aerial Ace', move3: 'Sand Attack', move4: 'Whirlwind', hp: 63, attack: 60, defense: 55, specialAttack: 50, specialDefense: 50, speed: 71)
Pokemon.create(id: 18, name: 'Pidgeot', type1: 'Normal', type2: 'Flying', move1: 'Fly', move2: 'Aerial Ace', move3: 'Whirlwind', move4: 'Take Down', hp: 83, attack: 80, defense: 75, specialAttack: 70, specialDefense: 70, speed: 101)
Pokemon.create(id: 19, name: 'Rattata', type1: 'Normal', type2: '', move1: 'Quick Attack', move2: 'Tackle', move3: 'Bite', move4: 'Thrash', hp: 30, attack: 56, defense: 35, specialAttack: 25, specialDefense: 35, speed: 72)
Pokemon.create(id: 20, name: 'Raticate', type1: 'Normal', type2: '', move1: 'Quick Attack', move2: 'Hyper Fang', move3: 'Scary Face', move4: 'Tackle', hp: 55, attack: 81, defense: 60, specialAttack: 50, specialDefense: 70, speed: 97)
Pokemon.create(id: 21, name: 'Spearow', type1: 'Normal', type2: 'Flying', move1: 'Gust', move2: 'Sand Attack', move3: 'Growl', move4: 'Leer', hp: 40, attack: 60, defense: 30, specialAttack: 31, specialDefense: 31, speed: 70)
Pokemon.create(id: 22, name: 'Fearow', type1: 'Normal', type2: 'Flying', move1: 'Fly', move2: 'Gust', move3: 'Drill Peck', move4: 'Fury Attack', hp: 65, attack: 90, defense: 65, specialAttack: 61, specialDefense: 61, speed: 100)
Pokemon.create(id: 23, name: 'Ekans', type1: 'Poison', type2: '', move1: 'Tackle', move2: 'Wrap', move3: 'Bite', move4: 'Poison Sting', hp: 35, attack: 60, defense: 44, specialAttack: 40, specialDefense: 54, speed: 55)
Pokemon.create(id: 24, name: 'Arbok', type1: 'Poison', type2: '', move1: 'Crunch', move2: 'Acid', move3: 'Poison Sting', move4: 'Wrap', hp: 60, attack: 85, defense: 69, specialAttack: 65, specialDefense: 79, speed: 80)
Pokemon.create(id: 25, name: 'Pikachu', type1: 'Electric', type2: '', move1: 'Thunder Wave', move2: 'Thunderbolt', move3: 'Thundershock', move4: 'Agility', hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90)
Pokemon.create(id: 26, name: 'Raichu', type1: 'Electric', type2: '', move1: 'Quick Attack', move2: 'Thunder', move3: 'Thunder Wave', move4: 'Thunder Punch', hp: 60, attack: 90, defense: 55, specialAttack: 90, specialDefense: 80, speed: 110)
Pokemon.create(id: 27, name: 'Sandshrew', type1: 'Ground', type2: '', move1: 'Sand Attack', move2: 'Scratch', move3: 'Tackle', move4: 'Growl', hp: 50, attack: 75, defense: 85, specialAttack: 20, specialDefense: 30, speed: 40)
Pokemon.create(id: 28, name: 'Sandslash', type1: 'Ground', type2: '', move1: 'Slash', move2: 'Dig', move3: 'Rollout', move4: 'Sand Attack', hp: 75, attack: 100, defense: 110, specialAttack: 45, specialDefense: 55, speed: 65)
Pokemon.create(id: 29, name: 'Nidoran', type1: 'Poison', type2: '', move1: 'Scratch', move2: 'Tackle', move3: 'Double Kick', move4: 'Thrash', hp: 55, attack: 47, defense: 52, specialAttack: 40, specialDefense: 40, speed: 41)
Pokemon.create(id: 30, name: 'Nidorina', type1: 'Poison', type2: '', move1: 'Scratch', move2: 'Double Kick', move3: 'Slash', move4: 'Tail Whip', hp: 70, attack: 62, defense: 67, specialAttack: 55, specialDefense: 55, speed: 56)
Pokemon.create(id: 31, name: 'Nidoqueen', type1: 'Poison', type2: 'Ground', move1: 'Earthquake', move2: 'Double Kick', move3: 'Body Slam', move4: 'Slash', hp: 90, attack: 92, defense: 87, specialAttack: 75, specialDefense: 85, speed: 76)
Pokemon.create(id: 32, name: 'Nidoran', type1: 'Poison', type2: '', move1: 'Scratch', move2: 'Tackle', move3: 'Double Kick', move4: 'Thrash', hp: 46, attack: 57, defense: 40, specialAttack: 40, specialDefense: 40, speed: 50)
Pokemon.create(id: 33, name: 'Nidorino', type1: 'Poison', type2: '', move1: 'Scratch', move2: 'Double Kick', move3: 'Slash', move4: 'Tail Whip', hp: 61, attack: 72, defense: 57, specialAttack: 55, specialDefense: 55, speed: 65)
Pokemon.create(id: 34, name: 'Nidoking', type1: 'Poison', type2: 'Ground', move1: 'Earthquake', move2: 'Double Kick', move3: 'Body Slam', move4: 'Mega Horn', hp: 81, attack: 102, defense: 77, specialAttack: 85, specialDefense: 75, speed: 85)
Pokemon.create(id: 35, name: 'Clefairy', type1: 'Normal', type2: '', move1: 'Doubleslap', move2: 'Pound', move3: 'Sing', move4: 'Minimize', hp: 70, attack: 45, defense: 48, specialAttack: 60, specialDefense: 65, speed: 35)
Pokemon.create(id: 36, name: 'Clefable', type1: 'Normal', type2: '', move1: 'Doubleslap', move2: 'Metronome', move3: 'Sing', move4: 'Pound', hp: 95, attack: 70, defense: 73, specialAttack: 96, specialDefense: 90, speed: 60)
Pokemon.create(id: 37, name: 'Vulpix', type1: 'Fire', type2: '', move1: 'Ember', move2: 'Roar', move3: 'Quick Attack', move4: 'Imprison', hp: 38, attack: 41, defense: 40, specialAttack: 50, specialDefense: 65, speed: 65)
Pokemon.create(id: 38, name: 'Ninetales', type1: 'Fire', type2: '', move1: 'Flamethrower', move2: 'Safeguard', move3: 'Fire Spin', move4: 'Quick Attack', hp: 73, attack: 76, defense: 75, specialAttack: 81, specialDefense: 100, speed: 100)
Pokemon.create(id: 39, name: 'Jigglypuff', type1: 'Normal', type2: '', move1: 'Sing', move2: 'Pound', move3: 'Defense Curl', move4: 'Rollout', hp: 115, attack: 45, defense: 20, specialAttack: 45, specialDefense: 25, speed: 20)
Pokemon.create(id: 40, name: 'Wigglytuff', type1: 'Normal', type2: '', move1: 'Rollout', move2: 'Rest', move3: 'Doubleslap', move4: 'Metrenome', hp: 140, attack: 70, defense: 45, specialAttack: 85, specialDefense: 50, speed: 45)
Pokemon.create(id: 41, name: 'Zubat', type1: 'Poison', type2: 'Flying', move1: 'Confuse Ray', move2: 'Supersonic', move3: 'Leech Life', move4: 'Mean Look', hp: 40, attack: 45, defense: 35, specialAttack: 30, specialDefense: 40, speed: 55)
Pokemon.create(id: 42, name: 'Golbat', type1: 'Poison', type2: 'Flying', move1: 'Crunch', move2: 'Supersonic', move3: 'Leech Life', move4: 'Wing Attack', hp: 75, attack: 80, defense: 70, specialAttack: 65, specialDefense: 76, speed: 90)
Pokemon.create(id: 43, name: 'Oddish', type1: 'Grass', type2: 'Poison', move1: 'Leech Life', move2: 'Tackle', move3: 'Tackle', move4: 'Thrash', hp: 45, attack: 50, defense: 55, specialAttack: 75, specialDefense: 65, speed: 30)
Pokemon.create(id: 44, name: 'Gloom', type1: 'Grass', type2: 'Poison', move1: 'Absorb', move2: 'Cut', move3: 'Mega Drain', move4: 'Poison Powder', hp: 60, attack: 65, defense: 70, specialAttack: 85, specialDefense: 75, speed: 40)
Pokemon.create(id: 45, name: 'Vileplume', type1: 'Grass', type2: 'Poison', move1: 'Giga Drain', move2: 'Cut', move3: 'Poison Power', move4: 'Solar Beam', hp: 75, attack: 80, defense: 85, specialAttack: 110, specialDefense: 90, speed: 50)
Pokemon.create(id: 46, name: 'Paris', type1: 'Bug', type2: 'Grass', move1: 'Scratch', move2: 'Leech Life', move3: 'Sweet Scent', move4: 'Tackle', hp: 35, attack: 70, defense: 55, specialAttack: 45, specialDefense: 55, speed: 25)
Pokemon.create(id: 47, name: 'Parasect', type1: 'Bug', type2: 'Grass', move1: 'Giga Drain', move2: 'Psybeam', move3: 'Leech Seed', move4: 'X-Scissor', hp: 60, attack: 95, defense: 80, specialAttack: 60, specialDefense: 80, speed: 30)
Pokemon.create(id: 48, name: 'Venonat', type1: 'Bug', type2: 'Poison', move1: 'Poison Sting', move2: 'Confusion', move3: 'Foresight', move4: 'Poison Powder', hp: 60, attack: 55, defense: 50, specialAttack: 40, specialDefense: 55, speed: 45)
Pokemon.create(id: 49, name: 'Venomoth', type1: 'Bug', type2: 'Poison', move1: 'Acid', move2: 'Psybeam', move3: 'Stun Spore', move4: 'Foresight', hp: 70, attack: 65, defense: 60, specialAttack: 90, specialDefense: 75, speed: 90)
Pokemon.create(id: 50, name: 'Diglett', type1: 'Ground', type2: '', move1: 'Dig', move2: 'Dig', move3: 'Dig', move4: 'Sand Attack', hp: 10, attack: 55, defense: 25, specialAttack: 35, specialDefense: 45, speed: 95)
Pokemon.create(id: 51, name: 'Dugtrio', type1: 'Ground', type2: '', move1: 'Dig', move2: 'Earthquake', move3: 'Sand Attack', move4: 'Tri Attack', hp: 35, attack: 80, defense: 50, specialAttack: 50, specialDefense: 70, speed: 120)
Pokemon.create(id: 52, name: 'Meowth', type1: 'Normal', type2: '', move1: 'Cut', move2: 'Feint Attack', move3: 'Payday', move4: 'Tackle', hp: 40, attack: 45, defense: 35, specialAttack: 40, specialDefense: 40, speed: 90)
Pokemon.create(id: 53, name: 'Persian', type1: 'Normal', type2: '', move1: 'Slash', move2: 'Swift', move3: 'Bite', move4: 'Payday', hp: 65, attack: 70, defense: 60, specialAttack: 65, specialDefense: 65, speed: 115)
Pokemon.create(id: 54, name: 'Psyduck', type1: 'Water', type2: '', move1: 'Confusion', move2: 'Bubble', move3: 'Tackle', move4: 'Tail Whip', hp: 50, attack: 52, defense: 48, specialAttack: 65, specialDefense: 50, speed: 55)
Pokemon.create(id: 55, name: 'Golduck', type1: 'Water', type2: '', move1: 'Bubblebeam', move2: 'Surf', move3: 'Psychic', move4: 'Slash', hp: 80, attack: 82, defense: 78, specialAttack: 95, specialDefense: 80, speed: 85)
Pokemon.create(id: 56, name: 'Mankey', type1: 'Fighting', type2: '', move1: 'Double Kick', move2: 'Low Kick', move3: 'Tackle', move4: 'Leer', hp: 40, attack: 80, defense: 35, specialAttack: 35, specialDefense: 45, speed: 70)
Pokemon.create(id: 57, name: 'Primeape', type1: 'Fighting', type2: '', move1: 'Karate Chop', move2: 'Low Kick', move3: 'Mega Punch', move4: 'Uproar', hp: 65, attack: 105, defense: 60, specialAttack: 60, specialDefense: 70, speed: 95)
Pokemon.create(id: 58, name: 'Growlithe', type1: 'Fire', type2: '', move1: 'Ember', move2: 'Bite', move3: 'Tackle', move4: 'Sunny Day', hp: 55, attack: 70, defense: 45, specialAttack: 70, specialDefense: 50, speed: 60)
Pokemon.create(id: 59, name: 'Arcanine', type1: 'Fire', type2: '', move1: 'Flamestrike', move2: 'Flamestrike', move3: 'Flamestrike', move4: 'Flamestrike', hp: 90, attack: 110, defense: 80, specialAttack: 100, specialDefense: 80, speed: 95)
Pokemon.create(id: 60, name: 'Poliwag', type1: 'Water', type2: '', move1: 'Water Gun', move2: 'Tackle', move3: 'Bubble', move4: 'Tail Whip', hp: 40, attack: 50, defense: 40, specialAttack: 40, specialDefense: 40, speed: 90)
Pokemon.create(id: 61, name: 'Poliwhirl', type1: 'Water', type2: '', move1: 'Mega Punch', move2: 'Bubblebeam', move3: 'Substitute', move4: 'Cut', hp: 65, attack: 65, defense: 65, specialAttack: 50, specialDefense: 50, speed: 90)
Pokemon.create(id: 62, name: 'Poliwrath', type1: 'Water', type2: 'Fighting', move1: 'Mega Punch', move2: 'Hydro Pump', move3: 'Slash', move4: 'Water Gun', hp: 90, attack: 95, defense: 95, specialAttack: 70, specialDefense: 90, speed: 70)
Pokemon.create(id: 63, name: 'Abra', type1: 'Psychic', type2: '', move1: 'Teleport', move2: 'Teleport', move3: 'Teleport', move4: 'Thrash', hp: 25, attack: 20, defense: 15, specialAttack: 105, specialDefense: 55, speed: 90)
Pokemon.create(id: 64, name: 'Kadabra', type1: 'Psychic', type2: '', move1: 'Psybeam', move2: 'Confusion', move3: 'Trick', move4: 'Tackle', hp: 40, attack: 35, defense: 30, specialAttack: 120, specialDefense: 70, speed: 105)
Pokemon.create(id: 65, name: 'Alakazam', type1: 'Psychic', type2: '', move1: 'Psychic', move2: 'Psybeam', move3: 'Future Sight', move4: 'Confusion', hp: 55, attack: 50, defense: 45, specialAttack: 135, specialDefense: 95, speed: 120)
Pokemon.create(id: 66, name: 'Machop', type1: 'Fighting', type2: '', move1: 'Karate Chop', move2: 'Foresight', move3: 'Tackle', move4: 'Tackle', hp: 70, attack: 80, defense: 50, specialAttack: 60, specialDefense: 65, speed: 35)
Pokemon.create(id: 67, name: 'Machoke', type1: 'Fighting', type2: '', move1: 'Low Kick', move2: 'Slam', move3: 'Double Kick', move4: 'Vital Throw', hp: 80, attack: 100, defense: 70, specialAttack: 50, specialDefense: 30, speed: 45)
Pokemon.create(id: 68, name: 'Machamp', type1: 'Fighting', type2: '', move1: 'Low Kick', move2: 'Seismic Toss', move3: 'Karate Chop', move4: 'Dynamic Punch', hp: 90, attack: 130, defense: 80, specialAttack: 65, specialDefense: 85, speed: 55)
Pokemon.create(id: 69, name: 'Bellsprout', type1: 'Grass', type2: 'Poison', move1: 'Vine Whip', move2: 'Tackle', move3: 'Tackle', move4: 'Thrash', hp: 50, attack: 75, defense: 35, specialAttack: 70, specialDefense: 30, speed: 40)
Pokemon.create(id: 70, name: 'Weepinbell', type1: 'Grass', type2: 'Poison', move1: 'Vine Whip', move2: 'Wrap', move3: 'Sweet Scent', move4: 'Acid', hp: 65, attack: 90, defense: 50, specialAttack: 85, specialDefense: 45, speed: 55)
Pokemon.create(id: 71, name: 'Victreebel', type1: 'Grass', type2: 'Poison', move1: 'Vine Whip', move2: 'Razor Leaf', move3: 'Sweet Scent', move4: 'Slam', hp: 80, attack: 105, defense: 65, specialAttack: 100, specialDefense: 70, speed: 70)


#item

Item.create(id: 1, name: 'Potion', price: 300, item_type: 'Medicine')
Item.create(id: 2, name: 'Super Potion', price: 600, item_type: 'Medicine')
Item.create(id: 3, name: 'Hyper Potion', price: 1200, item_type: 'Medicine')
Item.create(id: 4, name: 'Max Potion', price: 2100, item_type: 'Medicine')
Item.create(id: 5, name: 'Poke Ball', price: 1000, item_type: 'Pokeballs')
Item.create(id: 6, name: 'Great Ball', price: 2500, item_type: 'Pokeballs')
Item.create(id: 7, name: 'Ultra Ball', price: 5000, item_type: 'Pokeballs')
Item.create(id: 8, name: 'Master Ball', price: 25000, item_type: 'Pokeballs')
Item.create(id: 9, name: 'Leaf Stone', price: 6000, item_type: 'Evolution_Stone')
Item.create(id: 10, name: 'Water Stone', price: 6000, item_type: 'Evolution_Stone')
Item.create(id: 11, name: 'Thunder Stone', price: 6000, item_type: 'Evolution_Stone')
Item.create(id: 12, name: 'Fire Stone', price: 6000, item_type: 'Evolution_Stone')
Item.create(id: 13, name: 'Moon Stone', price: 6000, item_type: 'Evolution_Stone')